package me.shijunjie.SiteAccountingSystem.mapper;

import java.util.List;
import me.shijunjie.SiteAccountingSystem.entity.EmployeeHour;
import me.shijunjie.SiteAccountingSystem.entity.EmployeeHourExample;
import org.apache.ibatis.annotations.Param;

public interface EmployeeHourMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_hour
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	long countByExample(EmployeeHourExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_hour
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int deleteByExample(EmployeeHourExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_hour
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_hour
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int insert(EmployeeHour record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_hour
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int insertSelective(EmployeeHour record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_hour
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	List<EmployeeHour> selectByExample(EmployeeHourExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_hour
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	EmployeeHour selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_hour
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByExampleSelective(@Param("record") EmployeeHour record, @Param("example") EmployeeHourExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_hour
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByExample(@Param("record") EmployeeHour record, @Param("example") EmployeeHourExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_hour
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByPrimaryKeySelective(EmployeeHour record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_hour
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByPrimaryKey(EmployeeHour record);
}