package me.shijunjie.SiteAccountingSystem.mapper;

import java.util.List;
import me.shijunjie.SiteAccountingSystem.entity.PayOut;
import me.shijunjie.SiteAccountingSystem.entity.PayOutExample;
import org.apache.ibatis.annotations.Param;

public interface PayOutMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_out
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	long countByExample(PayOutExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_out
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int deleteByExample(PayOutExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_out
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_out
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int insert(PayOut record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_out
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int insertSelective(PayOut record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_out
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	List<PayOut> selectByExample(PayOutExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_out
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	PayOut selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_out
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByExampleSelective(@Param("record") PayOut record, @Param("example") PayOutExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_out
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByExample(@Param("record") PayOut record, @Param("example") PayOutExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_out
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByPrimaryKeySelective(PayOut record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_out
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByPrimaryKey(PayOut record);
}