package me.shijunjie.SiteAccountingSystem.mapper;

import java.util.List;
import me.shijunjie.SiteAccountingSystem.entity.Project;
import me.shijunjie.SiteAccountingSystem.entity.ProjectExample;
import org.apache.ibatis.annotations.Param;

public interface ProjectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	long countByExample(ProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int deleteByExample(ProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int insert(Project record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int insertSelective(Project record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	List<Project> selectByExample(ProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	Project selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Project record, @Param("example") ProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByExample(@Param("record") Project record, @Param("example") ProjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByPrimaryKeySelective(Project record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByPrimaryKey(Project record);
}