package me.shijunjie.SiteAccountingSystem.mapper;

import java.util.List;
import me.shijunjie.SiteAccountingSystem.entity.TUser;
import me.shijunjie.SiteAccountingSystem.entity.TUserExample;
import org.apache.ibatis.annotations.Param;

public interface TUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	long countByExample(TUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int deleteByExample(TUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int deleteByPrimaryKey(String username);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int insert(TUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int insertSelective(TUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	List<TUser> selectByExample(TUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	TUser selectByPrimaryKey(String username);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TUser record, @Param("example") TUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByExample(@Param("record") TUser record, @Param("example") TUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByPrimaryKeySelective(TUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	int updateByPrimaryKey(TUser record);
}