package me.shijunjie.SiteAccountingSystem.entity;

import java.util.Date;

public class Bill {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.employee_id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Integer employeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.add_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.bill_json
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private String billJson;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.id
	 * @return  the value of bill.id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.id
	 * @param id  the value for bill.id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.employee_id
	 * @return  the value of bill.employee_id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.employee_id
	 * @param employeeId  the value for bill.employee_id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.add_time
	 * @return  the value of bill.add_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.add_time
	 * @param addTime  the value for bill.add_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.bill_json
	 * @return  the value of bill.bill_json
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public String getBillJson() {
		return billJson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.bill_json
	 * @param billJson  the value for bill.bill_json
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setBillJson(String billJson) {
		this.billJson = billJson;
	}
}