package me.shijunjie.SiteAccountingSystem.entity;

import java.util.Date;
import java.math.BigDecimal;

public class EmployeeHour {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee_hour.id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee_hour.employee_id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Integer employeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee_hour.add_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee_hour.working_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private BigDecimal workingTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee_hour.working_date
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Date workingDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee_hour.id
	 * @return  the value of employee_hour.id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee_hour.id
	 * @param id  the value for employee_hour.id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee_hour.employee_id
	 * @return  the value of employee_hour.employee_id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee_hour.employee_id
	 * @param employeeId  the value for employee_hour.employee_id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee_hour.add_time
	 * @return  the value of employee_hour.add_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee_hour.add_time
	 * @param addTime  the value for employee_hour.add_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee_hour.working_time
	 * @return  the value of employee_hour.working_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public BigDecimal getWorkingTime() {
		return workingTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee_hour.working_time
	 * @param workingTime  the value for employee_hour.working_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setWorkingTime(BigDecimal workingTime) {
		this.workingTime = workingTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee_hour.working_date
	 * @return  the value of employee_hour.working_date
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Date getWorkingDate() {
		return workingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee_hour.working_date
	 * @param workingDate  the value for employee_hour.working_date
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setWorkingDate(Date workingDate) {
		this.workingDate = workingDate;
	}

	@Override
	public String toString() {
		return "EmployeeHour [id=" + id + ", employeeId=" + employeeId + ", addTime=" + addTime + ", workingTime="
				+ workingTime + ", workingDate=" + workingDate + "]";
	}
	
	
}