package me.shijunjie.SiteAccountingSystem.entity;

import java.util.Date;

public class PayOut {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_out.id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_out.employee_id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Integer employeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_out.add_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_out.pay_out_amount
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Integer payOutAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_out.pay_out_date
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Date payOutDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_out.id
	 * @return  the value of pay_out.id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_out.id
	 * @param id  the value for pay_out.id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_out.employee_id
	 * @return  the value of pay_out.employee_id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Integer getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_out.employee_id
	 * @param employeeId  the value for pay_out.employee_id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_out.add_time
	 * @return  the value of pay_out.add_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_out.add_time
	 * @param addTime  the value for pay_out.add_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_out.pay_out_amount
	 * @return  the value of pay_out.pay_out_amount
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Integer getPayOutAmount() {
		return payOutAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_out.pay_out_amount
	 * @param payOutAmount  the value for pay_out.pay_out_amount
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setPayOutAmount(Integer payOutAmount) {
		this.payOutAmount = payOutAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_out.pay_out_date
	 * @return  the value of pay_out.pay_out_date
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Date getPayOutDate() {
		return payOutDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_out.pay_out_date
	 * @param payOutDate  the value for pay_out.pay_out_date
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setPayOutDate(Date payOutDate) {
		this.payOutDate = payOutDate;
	}
}