package me.shijunjie.SiteAccountingSystem.entity;

import java.util.Date;

public class Project {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.project_name
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private String projectName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.create_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.finish_flag
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private Integer finishFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.id
	 * @return  the value of project.id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.id
	 * @param id  the value for project.id
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.project_name
	 * @return  the value of project.project_name
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public String getProjectName() {
		return projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.project_name
	 * @param projectName  the value for project.project_name
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.create_time
	 * @return  the value of project.create_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.create_time
	 * @param createTime  the value for project.create_time
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.finish_flag
	 * @return  the value of project.finish_flag
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public Integer getFinishFlag() {
		return finishFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.finish_flag
	 * @param finishFlag  the value for project.finish_flag
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setFinishFlag(Integer finishFlag) {
		this.finishFlag = finishFlag;
	}
}