package me.shijunjie.SiteAccountingSystem.entity;

public class TUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.username
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userpwd
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	private String userpwd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.username
	 * @return  the value of t_user.username
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.username
	 * @param username  the value for t_user.username
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userpwd
	 * @return  the value of t_user.userpwd
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public String getUserpwd() {
		return userpwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userpwd
	 * @param userpwd  the value for t_user.userpwd
	 * @mbg.generated  Fri Nov 30 15:54:26 CST 2018
	 */
	public void setUserpwd(String userpwd) {
		this.userpwd = userpwd;
	}
}